safe: true
lsi: false
pygments: true
source: .
permalink: /:title/
baseurl: "/"
url: http://legal.imamopravoznati.org
exclude:
- ".*"
- "*.md"
- "Gemfile*"
- "CNAME"

owner:
  name: Code for Croatia
  contact: mailto:hi@codeforcroatia.org
  website: http://codeforcroatia.org
  github: https://github.com/codeforcroatia
  facebook: https://www.facebook.com/kodirajzahrvatsku

license:
  name: CC0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.hr

analytics:
  provider: google
  google:
    id: UA-32876029-x
