safe: true
lsi: false
pygments: true
source: .
permalink: /:title/
baseurl: "/"
url: http://legal.imamopravoznati.org
exclude:
- ".*"
- "*.md"
- "Gemfile*"
- "CNAME"

owner:
  name: Code for Croatia
  contact: https://mailhide.io/e/gJXmq9Xl
  website: http://codeforcroatia.org
  github: https://github.com/codeforcroatia
  facebook: https://www.facebook.com/kodirajzahrvatsku
  
project:
  name: Imamo pravo znati
  website: http://imamopravoznati.org

license:
  name: CC0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.hr

analytics:
  provider: google
  google:
    id: UA-46708458-8
